name: Deploy to cPanel

on:
  push:
    branches:
      - main # triggers on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # root of your repo
          server-dir: /public_html/test-autodeploy/ # your cpanel folder
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
